import type { Puzzle } from '../../src/lib/types';

export const HARD_BATCH_A: Puzzle[] = [
	{
		solution: [
			{ word: 'Power', emoji: '⚡' },
			{ word: 'House', emoji: '🏠' },
			{ word: 'Plant', emoji: '🪴' },
			{ word: 'Show', emoji: '🎭' },
			{ word: 'Room', emoji: '🛋️' },
			{ word: 'Service', emoji: '🛎️' },
			{ word: 'Food', emoji: '🍽️' },
			{ word: 'Court', emoji: '🏛️' },
			{ word: 'Order', emoji: '📋' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Together they name something dominant or high-powered.' },
			{ from: 1, to: 2, clue: 'A potted indoor resident is often one.' },
			{ from: 3, to: 4, clue: 'Retailers use this for a display space.' },
			{ from: 4, to: 5, clue: 'Hotels offer this to your door.' },
			{ from: 6, to: 7, clue: 'Mall dining often gathers in one.' },
			{ from: 7, to: 8, clue: 'A judge can issue one.' },
			{ from: 0, to: 3, clue: 'A flashy display of skill can be called this.' },
			{ from: 1, to: 4, clue: 'One is a basic part of the other.' },
			{ from: 2, to: 5, clue: 'Factories and utilities need this kind of maintenance.' },
			{ from: 3, to: 6, clue: 'Cooking competitions and expos are one kind.' },
			{ from: 4, to: 7, clue: 'Push them together and you get a legal venue.' },
			{ from: 5, to: 8, clue: 'Maintenance paperwork often uses one.' },
		],
	},
	{
		solution: [
			{ word: 'Night', emoji: '🌙' },
			{ word: 'Life', emoji: '🌱' },
			{ word: 'Style', emoji: '🧥' },
			{ word: 'Watch', emoji: '⌚' },
			{ word: 'Party', emoji: '🎉' },
			{ word: 'Line', emoji: '➖' },
			{ word: 'Dog', emoji: '🐕' },
			{ word: 'House', emoji: '🏠' },
			{ word: 'Dance', emoji: '💃' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'City centers wake up for it after dark.' },
			{ from: 1, to: 2, clue: 'Together they describe a way of living.' },
			{ from: 3, to: 4, clue: 'A synchronized group viewing goes by this name.' },
			{ from: 4, to: 5, clue: 'It can mean a shared phone circuit or an approved message.' },
			{ from: 6, to: 7, clue: 'Put together, it becomes punishment by metaphor.' },
			{ from: 7, to: 8, clue: 'One is both a genre and a club-floor style.' },
			{ from: 0, to: 3, clue: 'A graveyard shift can be this.' },
			{ from: 1, to: 4, clue: 'Someone unusually lively may be the life of it.' },
			{ from: 2, to: 5, clue: 'Fashion brands often call a collection a line.' },
			{ from: 3, to: 6, clue: 'One can monitor on behalf of the public.' },
			{ from: 4, to: 7, clue: 'Reverse them and you get a place known for loud gatherings.' },
			{ from: 5, to: 8, clue: 'Rows of people do this together.' },
		],
	},
	{
		solution: [
			{ word: 'Track', emoji: '🛤️' },
			{ word: 'Race', emoji: '🏁' },
			{ word: 'Day', emoji: '☀️' },
			{ word: 'Record', emoji: '🎙️' },
			{ word: 'Card', emoji: '🃏' },
			{ word: 'Court', emoji: '🏛️' },
			{ word: 'Player', emoji: '🎮' },
			{ word: 'Game', emoji: '🎲' },
			{ word: 'Order', emoji: '📋' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'One is where the other happens.' },
			{ from: 1, to: 2, clue: 'Fans circle this on the calendar.' },
			{ from: 3, to: 4, clue: 'Scores and results are often written on one.' },
			{ from: 4, to: 5, clue: 'A face card is also called this.' },
			{ from: 6, to: 7, clue: 'One participates in the other.' },
			{ from: 7, to: 8, clue: 'Rulebooks often specify an order of play.' },
			{ from: 0, to: 3, clue: 'Together they mean prior performance.' },
			{ from: 1, to: 4, clue: 'At the track, the program is called this.' },
			{ from: 2, to: 5, clue: 'The idiom is to have your day in one.' },
			{ from: 3, to: 6, clue: 'One famously spins the other.' },
			{ from: 4, to: 7, clue: 'One is used to play the other.' },
			{ from: 5, to: 8, clue: 'Legal authority can produce one.' },
		],
	},
	{
		solution: [
			{ word: 'Card', emoji: '🃏' },
			{ word: 'Game', emoji: '🎲' },
			{ word: 'Show', emoji: '🎭' },
			{ word: 'Time', emoji: '⏰' },
			{ word: 'Line', emoji: '➖' },
			{ word: 'Dance', emoji: '💃' },
			{ word: 'Party', emoji: '🎉' },
			{ word: 'House', emoji: '🏠' },
			{ word: 'Music', emoji: '🎵' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'One obvious use for the first is the second.' },
			{ from: 1, to: 2, clue: 'Television built a genre from the pair.' },
			{ from: 3, to: 4, clue: 'Push them together and you get chronology.' },
			{ from: 4, to: 5, clue: 'People arrange themselves for this.' },
			{ from: 6, to: 7, clue: 'Reverse them and it becomes a social venue.' },
			{ from: 7, to: 8, clue: 'One names a dance-music genre.' },
			{ from: 0, to: 3, clue: 'Reverse them and you get a workplace punch record.' },
			{ from: 1, to: 4, clue: 'Sports books post one for each matchup.' },
			{ from: 2, to: 5, clue: 'A staged routine can simply be this.' },
			{ from: 3, to: 6, clue: 'Reverse them and it becomes a celebration.' },
			{ from: 4, to: 7, clue: 'Brands and casinos both use a house line.' },
			{ from: 5, to: 8, clue: 'The first is often set to the second.' },
		],
	},
	{
		solution: [
			{ word: 'Clock', emoji: '🕒' },
			{ word: 'Radio', emoji: '📻' },
			{ word: 'Show', emoji: '🎭' },
			{ word: 'Alarm', emoji: '🚨' },
			{ word: 'Line', emoji: '➖' },
			{ word: 'Dance', emoji: '💃' },
			{ word: 'Fire', emoji: '🔥' },
			{ word: 'Power', emoji: '⚡' },
			{ word: 'House', emoji: '🏠' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Bedside electronics made this compound familiar.' },
			{ from: 1, to: 2, clue: 'Broadcasting builds a format from the pair.' },
			{ from: 3, to: 4, clue: 'A dedicated emergency contact can be called this.' },
			{ from: 4, to: 5, clue: 'The formation is part of the name.' },
			{ from: 6, to: 7, clue: 'Together they mean force or offensive strength.' },
			{ from: 7, to: 8, clue: 'Together they mean a dominant force.' },
			{ from: 0, to: 3, clue: 'Reverse them for a bedside staple.' },
			{ from: 1, to: 4, clue: 'Call-in programs open one.' },
			{ from: 2, to: 5, clue: 'A performance routine fits the phrase.' },
			{ from: 3, to: 6, clue: 'Reverse them for a building emergency.' },
			{ from: 4, to: 7, clue: 'Reverse them for the overhead utility link.' },
			{ from: 5, to: 8, clue: 'Reverse them for a club-music or dance style.' },
		],
	},
	{
		solution: [
			{ word: 'Face', emoji: '😀' },
			{ word: 'Time', emoji: '⏰' },
			{ word: 'Bomb', emoji: '💣' },
			{ word: 'Card', emoji: '🃏' },
			{ word: 'Show', emoji: '🎭' },
			{ word: 'Dog', emoji: '🐕' },
			{ word: 'Game', emoji: '🎲' },
			{ word: 'Point', emoji: '📍' },
			{ word: 'Guard', emoji: '💂' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'The pair can mean a video call or time together in person.' },
			{ from: 1, to: 2, clue: 'Together they mean delayed disaster.' },
			{ from: 3, to: 4, clue: 'Collectors gather at one.' },
			{ from: 4, to: 5, clue: 'One is bred or trained for competition.' },
			{ from: 6, to: 7, clue: 'One point can end a game or set.' },
			{ from: 7, to: 8, clue: 'Basketball gives this role to the ball handler.' },
			{ from: 0, to: 3, clue: 'Reverse them for a king, queen, or jack.' },
			{ from: 1, to: 4, clue: 'Reverse them for curtain-up time.' },
			{ from: 2, to: 5, clue: 'Security teams use one to sniff explosives.' },
			{ from: 3, to: 6, clue: 'Reverse them for an obvious pastime.' },
			{ from: 4, to: 7, clue: 'A highlight can be the point of a show.' },
			{ from: 5, to: 8, clue: 'Reverse them for a protective animal.' },
		],
	},
	{
		solution: [
			{ word: 'Watch', emoji: '⌚' },
			{ word: 'Party', emoji: '🎉' },
			{ word: 'Room', emoji: '🛋️' },
			{ word: 'Dog', emoji: '🐕' },
			{ word: 'House', emoji: '🏠' },
			{ word: 'Plant', emoji: '🪴' },
			{ word: 'Food', emoji: '🍽️' },
			{ word: 'Court', emoji: '🏛️' },
			{ word: 'Order', emoji: '📋' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Groups stream together under this label.' },
			{ from: 1, to: 2, clue: 'Venues often rent one out.' },
			{ from: 3, to: 4, clue: 'Put them together and it becomes punishment by metaphor.' },
			{ from: 4, to: 5, clue: 'A leafy resident by the window is one.' },
			{ from: 6, to: 7, clue: 'Mall diners know the phrase well.' },
			{ from: 7, to: 8, clue: 'A judge can issue it.' },
			{ from: 0, to: 3, clue: 'Reverse them for a public-interest monitor.' },
			{ from: 1, to: 4, clue: 'Reverse them for a place known for gatherings.' },
			{ from: 2, to: 5, clue: 'A houseplant can be described this way too.' },
			{ from: 3, to: 6, clue: 'Reverse them for the obvious pet aisle label.' },
			{ from: 4, to: 7, clue: 'Reverse them and it becomes a legal building.' },
			{ from: 5, to: 8, clue: 'Botany uses this taxonomic rank.' },
		],
	},
	{
		solution: [
			{ word: 'House', emoji: '🏠' },
			{ word: 'Music', emoji: '🎵' },
			{ word: 'Scene', emoji: '🎬' },
			{ word: 'Party', emoji: '🎉' },
			{ word: 'Line', emoji: '➖' },
			{ word: 'Dance', emoji: '💃' },
			{ word: 'Card', emoji: '🃏' },
			{ word: 'Game', emoji: '🎲' },
			{ word: 'Show', emoji: '🎭' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Together they name a club-driven genre.' },
			{ from: 1, to: 2, clue: 'Together they mean a local cultural world.' },
			{ from: 3, to: 4, clue: 'It can be politics or old phone tech.' },
			{ from: 4, to: 5, clue: 'Rows and rhythm go together here.' },
			{ from: 6, to: 7, clue: 'One is used to play the other.' },
			{ from: 7, to: 8, clue: 'Television made a whole genre from the pair.' },
			{ from: 0, to: 3, clue: 'Reverse them for an at-home celebration.' },
			{ from: 1, to: 4, clue: 'Critics may talk about a melodic line this way.' },
			{ from: 2, to: 5, clue: 'Film and theater both speak naturally of a dance scene.' },
			{ from: 3, to: 6, clue: 'Reverse them for an invitation.' },
			{ from: 4, to: 7, clue: 'Sports books post one for a matchup.' },
			{ from: 5, to: 8, clue: 'Reverse them for a staged performance.' },
		],
	},
	{
		solution: [
			{ word: 'Match', emoji: '🏅' },
			{ word: 'Point', emoji: '📍' },
			{ word: 'Guard', emoji: '💂' },
			{ word: 'Card', emoji: '🃏' },
			{ word: 'Show', emoji: '🎭' },
			{ word: 'Dog', emoji: '🐕' },
			{ word: 'Time', emoji: '⏰' },
			{ word: 'Bomb', emoji: '💣' },
			{ word: 'Squad', emoji: '👥' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'In tennis, it can end everything.' },
			{ from: 1, to: 2, clue: 'Basketball uses the phrase directly.' },
			{ from: 3, to: 4, clue: 'Collectors gather at one.' },
			{ from: 4, to: 5, clue: 'Breed competitions feature one.' },
			{ from: 6, to: 7, clue: 'Together they mean trouble set on a timer.' },
			{ from: 7, to: 8, clue: 'Explosive disposal teams go by this name.' },
			{ from: 0, to: 3, clue: 'Combat sports use this for the bout listing.' },
			{ from: 1, to: 4, clue: 'A highlight can be the point of the show.' },
			{ from: 2, to: 5, clue: 'Reverse them for a protective animal.' },
			{ from: 3, to: 6, clue: 'Reverse them for a punch-in record.' },
			{ from: 4, to: 7, clue: 'A flop is said to do this.' },
			{ from: 5, to: 8, clue: 'Police K-9 units are one.' },
		],
	},
	{
		solution: [
			{ word: 'Track', emoji: '🛤️' },
			{ word: 'Record', emoji: '🎙️' },
			{ word: 'Card', emoji: '🃏' },
			{ word: 'Race', emoji: '🏁' },
			{ word: 'Game', emoji: '🎲' },
			{ word: 'Show', emoji: '🎭' },
			{ word: 'Day', emoji: '☀️' },
			{ word: 'Time', emoji: '⏰' },
			{ word: 'Bomb', emoji: '💣' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Together they mean prior performance.' },
			{ from: 1, to: 2, clue: 'Results are often written on one.' },
			{ from: 3, to: 4, clue: 'A racing title in software is one.' },
			{ from: 4, to: 5, clue: 'Television built a whole genre around it.' },
			{ from: 6, to: 7, clue: 'Together they mean the daylight hours.' },
			{ from: 7, to: 8, clue: 'Together they mean delayed trouble.' },
			{ from: 0, to: 3, clue: 'One hosts the other.' },
			{ from: 1, to: 4, clue: 'Sports history is full of them.' },
			{ from: 2, to: 5, clue: 'Collectors gather at one.' },
			{ from: 3, to: 6, clue: 'Fans circle it on the calendar.' },
			{ from: 4, to: 7, clue: 'Together they mean when the action starts.' },
			{ from: 5, to: 8, clue: 'A stage act that fails is said to do this.' },
		],
	},
];

/*
Themes and dominant hard-relation families:
1. Retail / hospitality / legal workflow: compounds, semantic role links, institutional phrases.
2. Nightlife and social behavior: idioms, genre labels, public-interest compounds, reverse compounds.
3. Competition and legal language: race-track terms, card/game vocabulary, idiom ('day in court').
4. Social entertainment stack: reverse compounds, chronology term, betting-line language, genre labels.
5. Broadcast and energy: consumer-electronics compounds, emergency phrases, reverse compounds, performance vocabulary.
6. Communication and security: figurative/modern phrase ('face time'), event vocabulary, bomb-sniffing and sports-role compounds.
7. Parties, venues, and taxonomy: reverse compounds, mall/legal phrases, room/plant description, taxonomic rank.
8. Club culture and performance: genre labels, cultural-scene language, invitation wording, betting-line phrasing.
9. Competition, collectibles, and security: sports phrases, show-language figurative sense ('bomb'), K-9/security compounds.
10. Sports/media timing: track-record language, digital-game phrasing, collectible-event wording, figurative failure phrase.
*/