import type { Puzzle } from '../../src/lib/types';

export const HARD_BATCH_B: Puzzle[] = [
	{
		solution: [
			{ word: 'Man', emoji: '👨' },
			{ word: 'Foot', emoji: '🦶' },
			{ word: 'Locker', emoji: '🔒' },
			{ word: 'Snow', emoji: '❄️' },
			{ word: 'Ball', emoji: '⚽' },
			{ word: 'Room', emoji: '🚪' },
			{ word: 'Board', emoji: '🧩' },
			{ word: 'Game', emoji: '🎮' },
			{ word: 'Escape', emoji: '🏃' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Liveried servant, backward.' },
			{ from: 1, to: 2, clue: 'Barracks kit, shut away.' },
			{ from: 3, to: 4, clue: 'Thrown winter that grows.' },
			{ from: 4, to: 5, clue: 'Formal dancing wants one.' },
			{ from: 6, to: 7, clue: 'Tabletop rivalry.' },
			{ from: 7, to: 8, clue: 'Locked-door entertainment.' },
			{ from: 0, to: 3, clue: 'Built from weather and a carrot.' },
			{ from: 3, to: 6, clue: 'Winter gear for the slope.' },
			{ from: 1, to: 4, clue: 'The world game hides here.' },
			{ from: 4, to: 7, clue: 'Pastime in its broadest form.' },
			{ from: 2, to: 5, clue: 'Benches, towels, and echoes.' },
			{ from: 5, to: 8, clue: 'The puzzle genre with a timer.' },
		],
	},
	// Note: Ball flips between dance and sport, but Snow, Foot, Room, and Game pin each reading.
	{
		solution: [
			{ word: 'Sea', emoji: '🌊' },
			{ word: 'Life', emoji: '🌱' },
			{ word: 'Style', emoji: '🎨' },
			{ word: 'Coast', emoji: '🏖️' },
			{ word: 'Line', emoji: '➖' },
			{ word: 'Dance', emoji: '💃' },
			{ word: 'Clear', emoji: '✨' },
			{ word: 'Up', emoji: '⬆️' },
			{ word: 'Step', emoji: '👣' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Reef inventory.' },
			{ from: 1, to: 2, clue: 'Habit as identity.' },
			{ from: 3, to: 4, clue: 'Map edge.' },
			{ from: 4, to: 5, clue: 'Rows become rhythm.' },
			{ from: 6, to: 7, clue: 'Order restored.' },
			{ from: 7, to: 8, clue: 'Advancement by one move.' },
			{ from: 0, to: 3, clue: 'Saltwater meets land.' },
			{ from: 3, to: 6, clue: 'Only then do you move.' },
			{ from: 1, to: 4, clue: 'A rope, then a metaphor.' },
			{ from: 4, to: 7, clue: 'Arrange yourselves.' },
			{ from: 2, to: 5, clue: 'Form expressed in motion.' },
			{ from: 5, to: 8, clue: 'One counted unit.' },
		],
	},
	// Note: Line splits between boundary, queue, and choreography; Coast, Life, Dance, and Up narrow it quickly.
	{
		solution: [
			{ word: 'Watch', emoji: '👀' },
			{ word: 'Night', emoji: '🌙' },
			{ word: 'Sleeper', emoji: '😴' },
			{ word: 'Dog', emoji: '🐕' },
			{ word: 'Guard', emoji: '💂' },
			{ word: 'Rail', emoji: '🛤️' },
			{ word: 'Sea', emoji: '🌊' },
			{ word: 'Coast', emoji: '🏖️' },
			{ word: 'Line', emoji: '➖' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'The shift without daylight.' },
			{ from: 1, to: 2, clue: 'A berth that departs late.' },
			{ from: 3, to: 4, clue: 'Teeth on duty.' },
			{ from: 4, to: 5, clue: 'Metal caution.' },
			{ from: 6, to: 7, clue: 'Where charts get jagged.' },
			{ from: 7, to: 8, clue: 'Cartography reduced.' },
			{ from: 0, to: 3, clue: 'Suspicion with fur.' },
			{ from: 3, to: 6, clue: 'Old sailor, bluntly.' },
			{ from: 1, to: 4, clue: 'Keys, torch, silence.' },
			{ from: 4, to: 7, clue: 'Cutters with authority.' },
			{ from: 2, to: 5, clue: 'Timber beneath the steel.' },
			{ from: 5, to: 8, clue: 'A route of iron.' },
		],
	},
	// Note: Watch and Guard can be noun or verb, but Night, Dog, Coast, and Rail force the security readings.
	{
		solution: [
			{ word: 'Tea', emoji: '🍵' },
			{ word: 'Party', emoji: '🎉' },
			{ word: 'Music', emoji: '🎵' },
			{ word: 'Tree', emoji: '🌳' },
			{ word: 'Line', emoji: '➖' },
			{ word: 'Dance', emoji: '💃' },
			{ word: 'Top', emoji: '🔝' },
			{ word: 'Up', emoji: '⬆️' },
			{ word: 'Step', emoji: '👣' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Porcelain or politics.' },
			{ from: 1, to: 2, clue: 'What raises the room.' },
			{ from: 3, to: 4, clue: 'Altitude\'s border.' },
			{ from: 4, to: 5, clue: 'Alignment turns social.' },
			{ from: 6, to: 7, clue: 'Recharge the balance.' },
			{ from: 7, to: 8, clue: 'Advancement by a stride.' },
			{ from: 0, to: 3, clue: 'The bottle by the sink hints here.' },
			{ from: 3, to: 6, clue: 'First place the wind arrives.' },
			{ from: 1, to: 4, clue: 'Script or shared wire.' },
			{ from: 4, to: 7, clue: 'Queue first.' },
			{ from: 2, to: 5, clue: 'Beat built to move to.' },
			{ from: 5, to: 8, clue: 'A single counted move.' },
		],
	},
	// Note: Party and Line both branch widely, but Tea, Music, Tree, and Up keep them in familiar compound lanes.
	{
		solution: [
			{ word: 'Book', emoji: '📖' },
			{ word: 'Club', emoji: '♣️' },
			{ word: 'House', emoji: '🏠' },
			{ word: 'Board', emoji: '🧩' },
			{ word: 'Room', emoji: '🚪' },
			{ word: 'Service', emoji: '🛎️' },
			{ word: 'Game', emoji: '🎮' },
			{ word: 'Escape', emoji: '🏃' },
			{ word: 'Route', emoji: '🗺️' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Monthly opinions in hardback.' },
			{ from: 1, to: 2, clue: 'Members only.' },
			{ from: 3, to: 4, clue: 'Where agendas harden.' },
			{ from: 4, to: 5, clue: 'A tray and a knock.' },
			{ from: 6, to: 7, clue: 'Puzzled confinement as leisure.' },
			{ from: 7, to: 8, clue: 'The memorized way out.' },
			{ from: 0, to: 3, clue: 'Toddler-proof pages.' },
			{ from: 3, to: 6, clue: 'Tabletop contest, again.' },
			{ from: 1, to: 4, clue: 'Reserved for members.' },
			{ from: 4, to: 7, clue: 'Locked-room recreation.' },
			{ from: 2, to: 5, clue: 'Domestic labor by category.' },
			{ from: 5, to: 8, clue: 'The road a driver repeats.' },
		],
	},
	// Note: Board and Service each have object/institution senses; Book, Game, Room, and Route keep them concrete.
	{
		solution: [
			{ word: 'Tree', emoji: '🌳' },
			{ word: 'Tea', emoji: '🍵' },
			{ word: 'Dance', emoji: '💃' },
			{ word: 'House', emoji: '🏠' },
			{ word: 'Party', emoji: '🎉' },
			{ word: 'Music', emoji: '🎵' },
			{ word: 'Dog', emoji: '🐕' },
			{ word: 'Food', emoji: '🍽️' },
			{ word: 'Soul', emoji: '👻' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'The oil gives it away.' },
			{ from: 1, to: 2, clue: 'A matinee social.' },
			{ from: 3, to: 4, clue: 'Too many shoes by the door.' },
			{ from: 4, to: 5, clue: 'What keeps the kitchen full.' },
			{ from: 6, to: 7, clue: 'Bagged loyalty.' },
			{ from: 7, to: 8, clue: 'Cuisine with its own canon.' },
			{ from: 0, to: 3, clue: 'Raised above the lawn.' },
			{ from: 3, to: 6, clue: 'Indoor pet, or exile backward.' },
			{ from: 1, to: 4, clue: 'Cups or rebellion.' },
			{ from: 4, to: 7, clue: 'Gone before dinner.' },
			{ from: 2, to: 5, clue: 'Meant for movement.' },
			{ from: 5, to: 8, clue: 'Genre, not metaphysics.' },
		],
	},
	// Note: Soul is the only real double-sense pivot; Food and Music make the cuisine and genre readings immediate.
	{
		solution: [
			{ word: 'Tower', emoji: '🗼' },
			{ word: 'Power', emoji: '⚡' },
			{ word: 'Horse', emoji: '🐎' },
			{ word: 'Water', emoji: '💧' },
			{ word: 'Plant', emoji: '🪴' },
			{ word: 'Food', emoji: '🍽️' },
			{ word: 'Gate', emoji: '🚪' },
			{ word: 'House', emoji: '🏠' },
			{ word: 'Dog', emoji: '🐕' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Steel lattice and current.' },
			{ from: 1, to: 2, clue: 'Engines still borrow the animal.' },
			{ from: 3, to: 4, clue: 'Municipal chemistry.' },
			{ from: 4, to: 5, clue: 'Granules by the shed.' },
			{ from: 6, to: 7, clue: 'An entrance with walls.' },
			{ from: 7, to: 8, clue: 'Indoor pet, or compound backward.' },
			{ from: 0, to: 3, clue: 'The skyline cistern.' },
			{ from: 3, to: 6, clue: 'A hotel name that escaped into shorthand.' },
			{ from: 1, to: 4, clue: 'Generation happens here.' },
			{ from: 4, to: 7, clue: 'A potted resident.' },
			{ from: 2, to: 5, clue: 'Stable rations.' },
			{ from: 5, to: 8, clue: 'Mascot on the kibble bag.' },
		],
	},
	// Note: Plant flips between factory and organism; Power, Water, House, and Food separate those senses cleanly.
	{
		solution: [
			{ word: 'Green', emoji: '🟩' },
			{ word: 'Room', emoji: '🚪' },
			{ word: 'Party', emoji: '🎉' },
			{ word: 'House', emoji: '🏠' },
			{ word: 'Service', emoji: '🛎️' },
			{ word: 'Food', emoji: '🍽️' },
			{ word: 'School', emoji: '🏫' },
			{ word: 'Public', emoji: '🏛️' },
			{ word: 'Market', emoji: '🛒' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Backstage, not yet seen.' },
			{ from: 1, to: 2, clue: 'A venue booked for noise.' },
			{ from: 3, to: 4, clue: 'Domestic labor by name.' },
			{ from: 4, to: 5, clue: 'The apron-and-invoice trade.' },
			{ from: 6, to: 7, clue: 'State funded, plainly.' },
			{ from: 7, to: 8, clue: 'Open-air commerce.' },
			{ from: 0, to: 3, clue: 'Glass and humidity.' },
			{ from: 3, to: 6, clue: 'Home-like, but older: read it backward.' },
			{ from: 1, to: 4, clue: 'The hotel knock.' },
			{ from: 4, to: 7, clue: 'Civic obligation as a phrase.' },
			{ from: 2, to: 5, clue: 'Skewers before supper.' },
			{ from: 5, to: 8, clue: 'Produce under canvas.' },
		],
	},
	// Note: Service shifts between hospitality and civics; Room, Food, and Public keep each reading from drifting.
	{
		solution: [
			{ word: 'Skin', emoji: '🧴' },
			{ word: 'Boil', emoji: '♨️' },
			{ word: 'Water', emoji: '💧' },
			{ word: 'Drum', emoji: '🥁' },
			{ word: 'Roll', emoji: '🌀' },
			{ word: 'Tide', emoji: '🌊' },
			{ word: 'Stick', emoji: '🪵' },
			{ word: 'Thunder', emoji: '🌩️' },
			{ word: 'Storm', emoji: '⛈️' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Dermatology, not cooking.' },
			{ from: 1, to: 2, clue: 'Kettle logic.' },
			{ from: 3, to: 4, clue: 'Suspense on snares.' },
			{ from: 4, to: 5, clue: 'Tuscaloosa knows it.' },
			{ from: 6, to: 7, clue: 'Stadium noise in foam form.' },
			{ from: 7, to: 8, clue: 'Sky percussion with weather attached.' },
			{ from: 0, to: 3, clue: 'What the mallet strikes.' },
			{ from: 3, to: 6, clue: 'One of the pair in hand.' },
			{ from: 1, to: 4, clue: 'The vigorous version.' },
			{ from: 4, to: 7, clue: 'Sound crossing the hills.' },
			{ from: 2, to: 5, clue: 'Moon-pulled motion.' },
			{ from: 5, to: 8, clue: 'When the surge turns mean.' },
		],
	},
	// Note: Roll swings between motion, music, and slogan; Drum, Boil, Tide, and Thunder keep the intended readings separate.
	{
		solution: [
			{ word: 'Court', emoji: '⚖️' },
			{ word: 'Night', emoji: '🌙' },
			{ word: 'School', emoji: '🏫' },
			{ word: 'Traffic', emoji: '🚦' },
			{ word: 'Light', emoji: '💡' },
			{ word: 'House', emoji: '🏠' },
			{ word: 'Signal', emoji: '📶' },
			{ word: 'Green', emoji: '🟩' },
			{ word: 'Tea', emoji: '🍵' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A judge after dark.' },
			{ from: 1, to: 2, clue: 'Classes after work.' },
			{ from: 3, to: 4, clue: 'Permission in three colors.' },
			{ from: 4, to: 5, clue: 'Warning on the rocks.' },
			{ from: 6, to: 7, clue: 'Go, without words.' },
			{ from: 7, to: 8, clue: 'Leaf, not bag dust.' },
			{ from: 0, to: 3, clue: 'Where speeding tickets end up.' },
			{ from: 3, to: 6, clue: 'The formal term, less poetic.' },
			{ from: 1, to: 4, clue: 'A small defense against the dark.' },
			{ from: 4, to: 7, clue: 'Proceed, or an eco shade.' },
			{ from: 2, to: 5, clue: 'One-room compound, backward.' },
			{ from: 5, to: 8, clue: 'A quiet room built around a pot.' },
		],
	},
	// Note: Light carries object, permission, and color senses; Traffic, Night, Green, House, and Court disambiguate each one.
];