import type { Puzzle } from '../../src/lib/types';

export const STANDARD_BATCH_D: Puzzle[] = [
	{
		solution: [
			{ word: 'Cab', emoji: '🚚' },
			{ word: 'Taxi', emoji: '🚕' },
			{ word: 'Stand', emoji: '🪧' },
			{ word: 'Truck', emoji: '🚛' },
			{ word: 'Driver', emoji: '🧑‍✈️' },
			{ word: 'Bus', emoji: '🚌' },
			{ word: 'Delivery', emoji: '📦' },
			{ word: 'Route', emoji: '🗺️' },
			{ word: 'Stop', emoji: '🚏' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A taxi cab is hailed at the curb.' },
			{ from: 1, to: 2, clue: 'A taxi stand is where cabs queue for fares.' },
			{ from: 3, to: 4, clue: 'A truck driver moves freight from depot to depot.' },
			{ from: 4, to: 5, clue: 'A bus driver follows the route and the schedule.' },
			{ from: 6, to: 7, clue: 'A delivery route strings many stops into one run.' },
			{ from: 7, to: 8, clue: 'A route is made up of planned stops.' },
			{ from: 0, to: 3, clue: 'The cab is the front section of a truck.' },
			{ from: 1, to: 4, clue: 'A taxi driver works the city streets for hire.' },
			{ from: 2, to: 5, clue: 'A bus stand gives riders a place to wait.' },
			{ from: 3, to: 6, clue: 'A delivery truck drops parcels block by block.' },
			{ from: 4, to: 7, clue: 'A driver follows an assigned route through the city.' },
			{ from: 5, to: 8, clue: 'A bus stop marks where riders board and exit.' },
		],
	},
	{
		solution: [
			{ word: 'Ticket', emoji: '🎫' },
			{ word: 'Zoo', emoji: '🦁' },
			{ word: 'Animal', emoji: '🐾' },
			{ word: 'Gate', emoji: '🚪' },
			{ word: 'Keeper', emoji: '🧑‍🌾' },
			{ word: 'Book', emoji: '📘' },
			{ word: 'Front', emoji: '🏁' },
			{ word: 'House', emoji: '🏠' },
			{ word: 'Guest', emoji: '🧳' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A zoo ticket gets you through the turnstile.' },
			{ from: 1, to: 2, clue: 'A zoo houses animals from around the world.' },
			{ from: 3, to: 4, clue: 'A gatekeeper controls who gets in.' },
			{ from: 4, to: 5, clue: 'A bookkeeper keeps the accounts straight.' },
			{ from: 6, to: 7, clue: 'Front of house handles the public-facing side.' },
			{ from: 7, to: 8, clue: 'A houseguest stays overnight with a host.' },
			{ from: 0, to: 3, clue: 'A ticket gate checks entry before you pass.' },
			{ from: 1, to: 4, clue: 'A zookeeper feeds animals and keeps enclosures in order.' },
			{ from: 2, to: 5, clue: 'An animal book is full of species facts and pictures.' },
			{ from: 3, to: 6, clue: 'The front gate is the main entrance to a place.' },
			{ from: 4, to: 7, clue: 'A housekeeper keeps rooms clean and ready.' },
			{ from: 5, to: 8, clue: 'A guest book collects names and short messages.' },
		],
	},
	{
		solution: [
			{ word: 'City', emoji: '🏙️' },
			{ word: 'Bus', emoji: '🚌' },
			{ word: 'Stop', emoji: '🚏' },
			{ word: 'Street', emoji: '🛣️' },
			{ word: 'Sign', emoji: '🚸' },
			{ word: 'Traffic', emoji: '🚦' },
			{ word: 'Bike', emoji: '🚲' },
			{ word: 'Lane', emoji: '↔️' },
			{ word: 'Driver', emoji: '🧑‍✈️' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A city bus carries commuters across town.' },
			{ from: 1, to: 2, clue: 'A bus stop marks where riders wait.' },
			{ from: 3, to: 4, clue: 'A street sign tells you where you are.' },
			{ from: 4, to: 5, clue: 'Traffic signs control how vehicles move.' },
			{ from: 6, to: 7, clue: 'A bike lane gives cyclists dedicated space.' },
			{ from: 7, to: 8, clue: 'A driver is expected to stay in the correct lane.' },
			{ from: 0, to: 3, clue: 'A city street is part of daily urban life.' },
			{ from: 1, to: 4, clue: 'A bus sign shows route numbers or arrival info.' },
			{ from: 2, to: 5, clue: 'A stop sign forces traffic to pause.' },
			{ from: 3, to: 6, clue: 'A street bike is built for paved roads.' },
			{ from: 4, to: 7, clue: 'A lane sign tells drivers which way they may go.' },
			{ from: 5, to: 8, clue: 'A driver has to read the traffic ahead.' },
		],
	},
	{
		solution: [
			{ word: 'Police', emoji: '👮' },
			{ word: 'Horse', emoji: '🐎' },
			{ word: 'Shoe', emoji: '👞' },
			{ word: 'Stable', emoji: '🏇' },
			{ word: 'Groom', emoji: '🧑‍🌾' },
			{ word: 'Brush', emoji: '🪮' },
			{ word: 'Race', emoji: '🏁' },
			{ word: 'Track', emoji: '🛤️' },
			{ word: 'Rider', emoji: '🏇' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Mounted police patrol on horseback.' },
			{ from: 1, to: 2, clue: 'A horseshoe protects the hoof.' },
			{ from: 3, to: 4, clue: 'A stable groom cares for the horses every day.' },
			{ from: 4, to: 5, clue: 'A groom uses a brush to clean a horse\'s coat.' },
			{ from: 6, to: 7, clue: 'A race is run on a track.' },
			{ from: 7, to: 8, clue: 'A rider circles the track during training.' },
			{ from: 0, to: 3, clue: 'Mounted police keep their horses in a stable.' },
			{ from: 1, to: 4, clue: 'A groom gets a horse ready for work or show.' },
			{ from: 2, to: 5, clue: 'A shoe brush cleans dirt from leather.' },
			{ from: 3, to: 6, clue: 'A racing stable houses horses built for speed.' },
			{ from: 4, to: 7, clue: 'A groom prepares horses before they go to the track.' },
			{ from: 5, to: 8, clue: 'A rider brushes down the horse after a session.' },
		],
	},
	{
		solution: [
			{ word: 'River', emoji: '🏞️' },
			{ word: 'Ferry', emoji: '⛴️' },
			{ word: 'Boat', emoji: '🚤' },
			{ word: 'Harbor', emoji: '⚓' },
			{ word: 'Dock', emoji: '🪝' },
			{ word: 'Crane', emoji: '🏗️' },
			{ word: 'Cargo', emoji: '📦' },
			{ word: 'Ship', emoji: '🚢' },
			{ word: 'Operator', emoji: '🕹️' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A river ferry carries people across the water.' },
			{ from: 1, to: 2, clue: 'A ferry is a boat built for passengers or cars.' },
			{ from: 3, to: 4, clue: 'A harbor dock is where vessels tie up.' },
			{ from: 4, to: 5, clue: 'A dock crane lifts heavy cargo.' },
			{ from: 6, to: 7, clue: 'A cargo ship carries containers overseas.' },
			{ from: 7, to: 8, clue: 'A ship operator runs commercial vessels.' },
			{ from: 0, to: 3, clue: 'A river can widen into a working harbor.' },
			{ from: 1, to: 4, clue: 'A ferry pulls into the dock at each stop.' },
			{ from: 2, to: 5, clue: 'A crane can lift a small boat out of the water.' },
			{ from: 3, to: 6, clue: 'Cargo moves through the harbor in huge volumes.' },
			{ from: 4, to: 7, clue: 'A ship lies alongside a dock while loading.' },
			{ from: 5, to: 8, clue: 'A crane operator controls the hoist.' },
		],
	},
	{
		solution: [
			{ word: 'Market', emoji: '🛒' },
			{ word: 'Town', emoji: '🏘️' },
			{ word: 'Square', emoji: '◻️' },
			{ word: 'Food', emoji: '🍜' },
			{ word: 'Hall', emoji: '🏛️' },
			{ word: 'Dance', emoji: '💃' },
			{ word: 'Street', emoji: '🛣️' },
			{ word: 'City', emoji: '🌆' },
			{ word: 'Club', emoji: '🎷' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A town market fills the center on busy days.' },
			{ from: 1, to: 2, clue: 'A town square sits at the civic heart of town.' },
			{ from: 3, to: 4, clue: 'A food hall gathers many counters under one roof.' },
			{ from: 4, to: 5, clue: 'A dance hall is built for music and movement.' },
			{ from: 6, to: 7, clue: 'A city street stays busy from morning to night.' },
			{ from: 7, to: 8, clue: 'A city club comes alive after dark.' },
			{ from: 0, to: 3, clue: 'A food market sells produce, bread, and fresh meals.' },
			{ from: 1, to: 4, clue: 'Town hall is where local government meets.' },
			{ from: 2, to: 5, clue: 'A square dance is called in sets.' },
			{ from: 3, to: 6, clue: 'Street food is cooked to eat on the go.' },
			{ from: 4, to: 7, clue: 'City hall houses the mayor and city offices.' },
			{ from: 5, to: 8, clue: 'A dance club fills up once the music starts.' },
		],
	},
	{
		solution: [
			{ word: 'Bus', emoji: '🚌' },
			{ word: 'Driver', emoji: '🧑‍✈️' },
			{ word: 'Seat', emoji: '💺' },
			{ word: 'Station', emoji: '🚉' },
			{ word: 'Train', emoji: '🚆' },
			{ word: 'Coach', emoji: '🚞' },
			{ word: 'Rail', emoji: '🛤️' },
			{ word: 'Track', emoji: '🏃' },
			{ word: 'Team', emoji: '👥' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A bus driver keeps the route moving.' },
			{ from: 1, to: 2, clue: 'The driver sits in the front seat.' },
			{ from: 3, to: 4, clue: 'A train station is where passengers board.' },
			{ from: 4, to: 5, clue: 'A coach is one car of a train.' },
			{ from: 6, to: 7, clue: 'Rail is laid along the track.' },
			{ from: 7, to: 8, clue: 'A track team trains for running events.' },
			{ from: 0, to: 3, clue: 'A bus station gathers many routes in one place.' },
			{ from: 1, to: 4, clue: 'A train driver controls the engine and brakes.' },
			{ from: 2, to: 5, clue: 'A coach seat folds down for the journey.' },
			{ from: 3, to: 6, clue: 'A rail station serves trains instead of cars.' },
			{ from: 4, to: 7, clue: 'A train runs on track, not on roads.' },
			{ from: 5, to: 8, clue: 'A coach trains the team.' },
		],
	},
	{
		solution: [
			{ word: 'Transit', emoji: '🚇' },
			{ word: 'Train', emoji: '🚆' },
			{ word: 'Engine', emoji: '🚂' },
			{ word: 'Police', emoji: '👮' },
			{ word: 'Station', emoji: '🚉' },
			{ word: 'Fire', emoji: '🔥' },
			{ word: 'Dog', emoji: '🐕' },
			{ word: 'House', emoji: '🏠' },
			{ word: 'Alarm', emoji: '🚨' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Transit trains move commuters through the city.' },
			{ from: 1, to: 2, clue: 'A train engine pulls the cars behind it.' },
			{ from: 3, to: 4, clue: 'A police station is the base for a precinct.' },
			{ from: 4, to: 5, clue: 'A fire station houses engines and crews.' },
			{ from: 6, to: 7, clue: 'A doghouse gives a pet shelter outside.' },
			{ from: 7, to: 8, clue: 'A house alarm warns of danger or intrusion.' },
			{ from: 0, to: 3, clue: 'Transit police patrol stations and platforms.' },
			{ from: 1, to: 4, clue: 'A train station is where the journey begins.' },
			{ from: 2, to: 5, clue: 'A fire engine is built to answer emergencies.' },
			{ from: 3, to: 6, clue: 'A police dog helps track suspects and scents.' },
			{ from: 4, to: 7, clue: 'A station house is the building behind the badge.' },
			{ from: 5, to: 8, clue: 'A fire alarm tells everyone to get out.' },
		],
	},
	{
		solution: [
			{ word: 'School', emoji: '🏫' },
			{ word: 'Bus', emoji: '🚌' },
			{ word: 'Route', emoji: '🗺️' },
			{ word: 'Desk', emoji: '🪑' },
			{ word: 'Job', emoji: '💼' },
			{ word: 'Service', emoji: '🛎️' },
			{ word: 'Teacher', emoji: '🧑‍🏫' },
			{ word: 'Aide', emoji: '🙋' },
			{ word: 'Help', emoji: '🆘' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A school bus picks students up each morning.' },
			{ from: 1, to: 2, clue: 'A bus route lists the planned stops in order.' },
			{ from: 3, to: 4, clue: 'A desk job keeps you working indoors.' },
			{ from: 4, to: 5, clue: 'A service job often means dealing with the public.' },
			{ from: 6, to: 7, clue: 'A teacher\'s aide supports the classroom.' },
			{ from: 7, to: 8, clue: 'An aide is there to help when needed.' },
			{ from: 0, to: 3, clue: 'A school desk is part of a classroom setup.' },
			{ from: 1, to: 4, clue: 'Driving a bus can be a city job.' },
			{ from: 2, to: 5, clue: 'Route service depends on fixed timing and stops.' },
			{ from: 3, to: 6, clue: 'A teacher works from a desk during the school day.' },
			{ from: 4, to: 7, clue: 'Being an aide is a support job.' },
			{ from: 5, to: 8, clue: 'A help service answers questions when people get stuck.' },
		],
	},
	{
		solution: [
			{ word: 'Guest', emoji: '🧳' },
			{ word: 'Book', emoji: '📗' },
			{ word: 'Club', emoji: '🎟️' },
			{ word: 'Gate', emoji: '🚪' },
			{ word: 'Keeper', emoji: '🧑‍🌾' },
			{ word: 'Shop', emoji: '🏪' },
			{ word: 'House', emoji: '🏠' },
			{ word: 'Pet', emoji: '🐶' },
			{ word: 'Food', emoji: '🥣' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A guest book records who came by.' },
			{ from: 1, to: 2, clue: 'A book club picks a title to discuss together.' },
			{ from: 3, to: 4, clue: 'A gatekeeper decides who gets through.' },
			{ from: 4, to: 5, clue: 'A shopkeeper runs the store floor and the till.' },
			{ from: 6, to: 7, clue: 'A house pet lives with people at home.' },
			{ from: 7, to: 8, clue: 'Pet food is sold for cats, dogs, and more.' },
			{ from: 0, to: 3, clue: 'A houseguest stays in someone else\'s home.' },
			{ from: 1, to: 4, clue: 'A bookkeeper handles accounts and balances.' },
			{ from: 2, to: 5, clue: 'A club shop sells team gear and member items.' },
			{ from: 3, to: 6, clue: 'A gatehouse stands beside the main entrance.' },
			{ from: 4, to: 7, clue: 'A pet keeper cares for animals every day.' },
			{ from: 5, to: 8, clue: 'A food shop sells produce and pantry basics.' },
		],
	},
];

/*
Concepts:
1. Taxi, truck, and bus operations.
2. Zoo entry, keeper jobs, and front-of-house hospitality.
3. City traffic, signage, and bike-lane street life.
4. Mounted police, horse care, and racing prep.
5. River ferry traffic, harbor loading, and ship operations.
6. Markets, civic spaces, nightlife, and street food.
7. Buses, trains, coaches, and track-based travel.
8. Transit stations, emergency services, and working dogs.
9. School transport, classroom work, and support roles.
10. Guest services, keeping roles, pet care, and retail.
The strongest relation types across the batch are everyday compounds and fixed phrases, role-object or role-place links, and straightforward use relationships, with only light reliance on broader city-life theming.
*/