import type { Puzzle } from '../../src/lib/types';

export const STANDARD_BATCH_A: Puzzle[] = [
	{
		solution: [
			{ word: 'Bag', emoji: '🛍️' },
			{ word: 'Tea', emoji: '🍵' },
			{ word: 'Break', emoji: '⏸️' },
			{ word: 'Paper', emoji: '📄' },
			{ word: 'Cup', emoji: '🥤' },
			{ word: 'Coffee', emoji: '☕' },
			{ word: 'Plate', emoji: '🍽️' },
			{ word: 'Cake', emoji: '🍰' },
			{ word: 'Mug', emoji: '🍺' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Tea bags hold the leaves.' },
			{ from: 1, to: 2, clue: 'A tea break is a common pause.' },
			{ from: 3, to: 4, clue: 'Paper cups are disposable.' },
			{ from: 4, to: 5, clue: 'Coffee is often served in a cup.' },
			{ from: 6, to: 7, clue: 'Cakes sit on plates.' },
			{ from: 7, to: 8, clue: 'A mug cake is made in a mug.' },
			{ from: 0, to: 3, clue: 'A bag can be made of paper.' },
			{ from: 1, to: 4, clue: 'Tea is served in a cup.' },
			{ from: 2, to: 5, clue: 'A coffee break is a familiar pause.' },
			{ from: 3, to: 6, clue: 'Paper plates are party basics.' },
			{ from: 4, to: 7, clue: 'A cupcake hides the cake in the cup.' },
			{ from: 5, to: 8, clue: 'Coffee is often served in a mug.' },
		],
	},
	{
		solution: [
			{ word: 'Score', emoji: '🎯' },
			{ word: 'Board', emoji: '🧩' },
			{ word: 'Room', emoji: '🚪' },
			{ word: 'Card', emoji: '🃏' },
			{ word: 'Game', emoji: '🎮' },
			{ word: 'Night', emoji: '🌙' },
			{ word: 'Business', emoji: '💼' },
			{ word: 'Plan', emoji: '📝' },
			{ word: 'Flight', emoji: '✈️' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Scores appear on a board.' },
			{ from: 1, to: 2, clue: 'A boardroom is a meeting room.' },
			{ from: 3, to: 4, clue: 'Cards are used in many games.' },
			{ from: 4, to: 5, clue: 'A game night is a common get-together.' },
			{ from: 6, to: 7, clue: 'Businesses run on plans.' },
			{ from: 7, to: 8, clue: 'A flight plan charts the route.' },
			{ from: 0, to: 3, clue: 'A scorecard records the score.' },
			{ from: 1, to: 4, clue: 'A board game sits on the table.' },
			{ from: 2, to: 5, clue: 'A room can be booked for the night.' },
			{ from: 3, to: 6, clue: 'A business card fits in a wallet.' },
			{ from: 4, to: 7, clue: 'A game plan is basic strategy.' },
			{ from: 5, to: 8, clue: 'Many red-eyes are night flights.' },
		],
	},
	{
		solution: [
			{ word: 'Road', emoji: '🛣️' },
			{ word: 'Trip', emoji: '🧳' },
			{ word: 'Wire', emoji: '🔌' },
			{ word: 'Stop', emoji: '🛑' },
			{ word: 'Sign', emoji: '🪧' },
			{ word: 'Post', emoji: '📍' },
			{ word: 'Night', emoji: '🌙' },
			{ word: 'Flight', emoji: '✈️' },
			{ word: 'Path', emoji: '🛤️' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A road trip is a classic holiday.' },
			{ from: 1, to: 2, clue: 'A tripwire catches a careless foot.' },
			{ from: 3, to: 4, clue: 'A stop sign gives the order.' },
			{ from: 4, to: 5, clue: 'A signpost points the way.' },
			{ from: 6, to: 7, clue: 'A night flight leaves after dark.' },
			{ from: 7, to: 8, clue: 'A flight path marks the route.' },
			{ from: 0, to: 3, clue: 'A roadside stop breaks up the drive.' },
			{ from: 1, to: 4, clue: 'Signs help guide a trip.' },
			{ from: 2, to: 5, clue: 'Wire is often stretched between posts.' },
			{ from: 3, to: 6, clue: 'A long journey can include a night stop.' },
			{ from: 4, to: 7, clue: 'Airports show flights on signs.' },
			{ from: 5, to: 8, clue: 'A guidepost can mark a path.' },
		],
	},
	{
		solution: [
			{ word: 'Sun', emoji: '🌞' },
			{ word: 'Screen', emoji: '📺' },
			{ word: 'Door', emoji: '🚪' },
			{ word: 'Moon', emoji: '🌙' },
			{ word: 'Light', emoji: '💡' },
			{ word: 'Bulb', emoji: '💡' },
			{ word: 'Night', emoji: '🌌' },
			{ word: 'Flight', emoji: '✈️' },
			{ word: 'Path', emoji: '🛤️' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Sunscreen protects skin.' },
			{ from: 1, to: 2, clue: 'A screen door lets air in.' },
			{ from: 3, to: 4, clue: 'Moonlight is light from the moon.' },
			{ from: 4, to: 5, clue: 'A bulb gives off light.' },
			{ from: 6, to: 7, clue: 'A night flight crosses the sky after dark.' },
			{ from: 7, to: 8, clue: 'A flight path marks the route.' },
			{ from: 0, to: 3, clue: 'The sun and moon share the sky.' },
			{ from: 1, to: 4, clue: 'Screens give off light.' },
			{ from: 2, to: 5, clue: 'A porch bulb often hangs by the door.' },
			{ from: 3, to: 6, clue: 'The moon is a night sight.' },
			{ from: 4, to: 7, clue: 'Runway lights guide flights.' },
			{ from: 5, to: 8, clue: 'Path lights use bulbs.' },
		],
	},
	{
		solution: [
			{ word: 'Band', emoji: '🎸' },
			{ word: 'Stand', emoji: '🪑' },
			{ word: 'Microphone', emoji: '🎤' },
			{ word: 'Sheet', emoji: '📄' },
			{ word: 'Music', emoji: '🎵' },
			{ word: 'Note', emoji: '🎶' },
			{ word: 'Guitar', emoji: '🎸' },
			{ word: 'String', emoji: '🧵' },
			{ word: 'Pick', emoji: '⛏️' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A bandstand is built for performers.' },
			{ from: 1, to: 2, clue: 'A microphone stand holds the mic.' },
			{ from: 3, to: 4, clue: 'Sheet music is printed on the page.' },
			{ from: 4, to: 5, clue: 'Notes make up music.' },
			{ from: 6, to: 7, clue: 'Guitars use strings.' },
			{ from: 7, to: 8, clue: 'A pick plucks the string.' },
			{ from: 0, to: 3, clue: 'A band reads from sheets or parts.' },
			{ from: 1, to: 4, clue: 'A music stand holds the pages up.' },
			{ from: 2, to: 5, clue: 'Singers hit notes into a microphone.' },
			{ from: 3, to: 6, clue: 'Guitar sheet music is sold in books.' },
			{ from: 4, to: 7, clue: 'String music is a familiar section title.' },
			{ from: 5, to: 8, clue: 'Players pick out a note.' },
		],
	},
	{
		solution: [
			{ word: 'Hen', emoji: '🐔' },
			{ word: 'Nest', emoji: '🪺' },
			{ word: 'Egg', emoji: '🥚' },
			{ word: 'Bee', emoji: '🐝' },
			{ word: 'Hive', emoji: '🐝🏠' },
			{ word: 'Honey', emoji: '🍯' },
			{ word: 'Cow', emoji: '🐄' },
			{ word: 'Barn', emoji: '🏚️' },
			{ word: 'Milk', emoji: '🥛' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Hens lay in nests.' },
			{ from: 1, to: 2, clue: 'Eggs rest in a nest.' },
			{ from: 3, to: 4, clue: 'Bees live in a hive.' },
			{ from: 4, to: 5, clue: 'Hives produce honey.' },
			{ from: 6, to: 7, clue: 'Cows stand in the barn.' },
			{ from: 7, to: 8, clue: 'A dairy barn leads to milk.' },
			{ from: 0, to: 3, clue: 'Both are familiar farm creatures.' },
			{ from: 1, to: 4, clue: 'Both are animal homes.' },
			{ from: 2, to: 5, clue: 'Both can appear on a breakfast table.' },
			{ from: 3, to: 6, clue: 'Both can be kept on a farm.' },
			{ from: 4, to: 7, clue: 'Both shelter living creatures.' },
			{ from: 5, to: 8, clue: 'Honey can sweeten warm milk.' },
		],
	},
	{
		solution: [
			{ word: 'Voice', emoji: '🗣️' },
			{ word: 'Mail', emoji: '✉️' },
			{ word: 'Box', emoji: '📦' },
			{ word: 'Text', emoji: '💬' },
			{ word: 'Message', emoji: '📨' },
			{ word: 'Board', emoji: '🪧' },
			{ word: 'Note', emoji: '📝' },
			{ word: 'Pad', emoji: '📓' },
			{ word: 'Paper', emoji: '📄' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Voicemail stores spoken messages.' },
			{ from: 1, to: 2, clue: 'A mailbox holds the mail.' },
			{ from: 3, to: 4, clue: 'A text message arrives on the phone.' },
			{ from: 4, to: 5, clue: 'A message board shows public notes.' },
			{ from: 6, to: 7, clue: 'A notepad is made for quick notes.' },
			{ from: 7, to: 8, clue: 'A paper pad sits on a desk.' },
			{ from: 0, to: 3, clue: 'Voice and text are two ways to send a message.' },
			{ from: 1, to: 4, clue: 'Mail carries messages.' },
			{ from: 2, to: 5, clue: 'Boxboard is a kind of paper stock.' },
			{ from: 3, to: 6, clue: 'A quick note can be sent as a text.' },
			{ from: 4, to: 7, clue: 'People jot messages on a pad.' },
			{ from: 5, to: 8, clue: 'Paperboard is another name for board-like paper.' },
		],
	},
	{
		solution: [
			{ word: 'Dog', emoji: '🐕' },
			{ word: 'House', emoji: '🏠' },
			{ word: 'Cat', emoji: '🐈' },
			{ word: 'Pet', emoji: '🐾' },
			{ word: 'Food', emoji: '🍲' },
			{ word: 'Bowl', emoji: '🥣' },
			{ word: 'Bird', emoji: '🐦' },
			{ word: 'Cage', emoji: '🐦🏠' },
			{ word: 'Seed', emoji: '🌾' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A doghouse shelters a dog.' },
			{ from: 1, to: 2, clue: 'A house cat stays indoors.' },
			{ from: 3, to: 4, clue: 'Pet food fills the cupboard.' },
			{ from: 4, to: 5, clue: 'Food goes in the bowl.' },
			{ from: 6, to: 7, clue: 'A cage holds a bird.' },
			{ from: 7, to: 8, clue: 'Seed belongs in a feeder or cage tray.' },
			{ from: 0, to: 3, clue: 'Dogs are common pets.' },
			{ from: 1, to: 4, clue: 'Food is kept in the house.' },
			{ from: 2, to: 5, clue: 'Cats eat from bowls.' },
			{ from: 3, to: 6, clue: 'Birds can be pets too.' },
			{ from: 4, to: 7, clue: 'Caged birds still need food.' },
			{ from: 5, to: 8, clue: 'A bowl can hold seed.' },
		],
	},
	{
		solution: [
			{ word: 'Sun', emoji: '🌞' },
			{ word: 'Flower', emoji: '🌼' },
			{ word: 'Pot', emoji: '🪴' },
			{ word: 'Garden', emoji: '🌷' },
			{ word: 'Plant', emoji: '🌿' },
			{ word: 'Food', emoji: '🥗' },
			{ word: 'Wall', emoji: '🧱' },
			{ word: 'Vine', emoji: '🍇' },
			{ word: 'Leaf', emoji: '🍃' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A sunflower turns to the light.' },
			{ from: 1, to: 2, clue: 'A flowerpot holds the bloom.' },
			{ from: 3, to: 4, clue: 'A plant can grow in a garden.' },
			{ from: 4, to: 5, clue: 'Plant food helps growth.' },
			{ from: 6, to: 7, clue: 'Vines climb walls.' },
			{ from: 7, to: 8, clue: 'A vine is covered in leaves.' },
			{ from: 0, to: 3, clue: 'Gardens need sun.' },
			{ from: 1, to: 4, clue: 'Flowers grow on plants.' },
			{ from: 2, to: 5, clue: 'A pot is used to cook food.' },
			{ from: 3, to: 6, clue: 'A wall can edge a garden.' },
			{ from: 4, to: 7, clue: 'A vine is a kind of plant.' },
			{ from: 5, to: 8, clue: 'Leafy greens are food.' },
		],
	},
	{
		solution: [
			{ word: 'Gift', emoji: '🎁' },
			{ word: 'Bag', emoji: '🛍️' },
			{ word: 'Tag', emoji: '🏷️' },
			{ word: 'Tea', emoji: '🍵' },
			{ word: 'Cup', emoji: '🥤' },
			{ word: 'Cake', emoji: '🎂' },
			{ word: 'Birthday', emoji: '🥳' },
			{ word: 'Party', emoji: '🎉' },
			{ word: 'Candles', emoji: '🕯️' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A gift bag wraps the present.' },
			{ from: 1, to: 2, clue: 'A bag tag helps identify luggage.' },
			{ from: 3, to: 4, clue: 'Tea is served in a cup.' },
			{ from: 4, to: 5, clue: 'A cupcake is a small cake.' },
			{ from: 6, to: 7, clue: 'A birthday party brings people together.' },
			{ from: 7, to: 8, clue: 'Candles decorate a party table.' },
			{ from: 0, to: 3, clue: 'Tea can be given as a gift.' },
			{ from: 1, to: 4, clue: 'Cups can be carried in a bag.' },
			{ from: 2, to: 5, clue: 'Bakery cakes often carry tags.' },
			{ from: 3, to: 6, clue: 'A birthday tea is a kind of party.' },
			{ from: 4, to: 7, clue: 'Party cups are disposable cups.' },
			{ from: 5, to: 8, clue: 'Candles belong on a cake.' },
		],
	},
];

/*
1. Cafe Break: checked that Bag, Plate, and Mug were pinned by drinkware and snack compounds rather than swapping freely.
2. Game Night: checked that Score and Business each had one dominant card/plan lane and did not create easy alternate rows.
3. Travel Signs: checked that Road, Sign, and Post stayed directional rather than collapsing into a generic transport theme.
4. Sky Lights: checked that Screen and Bulb were anchored to Light and Door, not drifting into vague tech-only links.
5. Music Gear: checked that Stand and String stayed musical through their neighbors instead of becoming generic object words.
6. Farm Morning: checked that the vertical farm clues stayed concrete homes/products rather than loose barnyard trivia.
7. Message Desk: checked that Box/Board/Paper were supported by specific communication or paper-stock readings.
8. Pet Home: checked that House, Cage, and Bowl were each tied to one pet-care role, limiting broad home-category swaps.
9. Garden Plot: checked that Pot, Wall, and Vine stayed gardening-specific rather than turning into general household links.
10. Birthday Tea: checked that Gift, Party, and Cake remained event-specific and did not open a broader shopping board.
*/