import type { Puzzle } from '../../src/lib/types';

export const STANDARD_BATCH_E: Puzzle[] = [
	{
		solution: [
			{ word: 'Paper', emoji: '📄' },
			{ word: 'Chain', emoji: '⛓️' },
			{ word: 'Dog', emoji: '🐕' },
			{ word: 'Clip', emoji: '📎' },
			{ word: 'Mail', emoji: '✉️' },
			{ word: 'Tag', emoji: '🏷️' },
			{ word: 'Board', emoji: '🪵' },
			{ word: 'Room', emoji: '🚪' },
			{ word: 'Service', emoji: '🛎️' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A paper chain is a classic classroom decoration.' },
			{ from: 1, to: 2, clue: 'A dog chain keeps a pet from wandering off.' },
			{ from: 3, to: 4, clue: 'A clip can hold a small pile of mail together.' },
			{ from: 4, to: 5, clue: 'A mailing tag travels with the parcel.' },
			{ from: 6, to: 7, clue: 'A boardroom is where the meeting usually starts.' },
			{ from: 7, to: 8, clue: 'Room service brings the tray to your door.' },
			{ from: 0, to: 3, clue: 'A paper clip is the obvious desk pairing.' },
			{ from: 3, to: 6, clue: 'A clipboard gives paper a firm backing.' },
			{ from: 1, to: 4, clue: 'Chain mail is the armored phrase hiding here.' },
			{ from: 4, to: 7, clue: 'A mail room keeps office deliveries sorted.' },
			{ from: 2, to: 5, clue: 'A dog tag hangs from a collar or uniform.' },
			{ from: 5, to: 8, clue: 'A service tag records repair or inspection work.' },
		],
	},
	{
		solution: [
			{ word: 'Door', emoji: '🚪' },
			{ word: 'Lock', emoji: '🔒' },
			{ word: 'Bike', emoji: '🚲' },
			{ word: 'Bell', emoji: '🔔' },
			{ word: 'Chain', emoji: '⛓️' },
			{ word: 'Ring', emoji: '💍' },
			{ word: 'Tower', emoji: '🗼' },
			{ word: 'Guard', emoji: '💂' },
			{ word: 'Tone', emoji: '🎵' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A door lock is the first layer of security.' },
			{ from: 1, to: 2, clue: 'A bike lock matters anywhere theft is easy.' },
			{ from: 3, to: 4, clue: 'A bell chain gives you something to pull.' },
			{ from: 4, to: 5, clue: 'A chain ring sits at the heart of a bicycle drivetrain.' },
			{ from: 6, to: 7, clue: 'A tower guard watches from the high point.' },
			{ from: 7, to: 8, clue: 'A guard’s tone usually tells you whether to come closer or move along.' },
			{ from: 0, to: 3, clue: 'A doorbell announces whoever is outside.' },
			{ from: 3, to: 6, clue: 'A bell tower is built to be heard across town.' },
			{ from: 1, to: 4, clue: 'A lock chain can secure a gate, locker, or bike.' },
			{ from: 4, to: 7, clue: 'A chain guard keeps grease and teeth away from clothing.' },
			{ from: 2, to: 5, clue: 'A bike can make a ring with its bell on the bars.' },
			{ from: 5, to: 8, clue: 'A ringtone is the sound your phone picks for callers.' },
		],
	},
	{
		solution: [
			{ word: 'Hotel', emoji: '🏨' },
			{ word: 'Bell', emoji: '🔔' },
			{ word: 'Desk', emoji: '🛎️' },
			{ word: 'Mail', emoji: '✉️' },
			{ word: 'Room', emoji: '🛏️' },
			{ word: 'Service', emoji: '🧳' },
			{ word: 'Box', emoji: '📦' },
			{ word: 'Office', emoji: '🏢' },
			{ word: 'Key', emoji: '🔑' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A hotel bell is there to summon help or announce arrival.' },
			{ from: 1, to: 2, clue: 'A bell sits on the front desk in plenty of lobbies.' },
			{ from: 3, to: 4, clue: 'A mail room keeps deliveries from getting lost.' },
			{ from: 4, to: 5, clue: 'Room service is one of the classic hotel perks.' },
			{ from: 6, to: 7, clue: 'The box office handles tickets and late arrivals.' },
			{ from: 7, to: 8, clue: 'An office key belongs to the person opening up in the morning.' },
			{ from: 0, to: 3, clue: 'Hotels still receive guest mail and parcels.' },
			{ from: 3, to: 6, clue: 'A mailbox is the standard place letters wait.' },
			{ from: 1, to: 4, clue: 'A room may have a bell for help or service.' },
			{ from: 4, to: 7, clue: 'An office is, at the simplest level, just another room with a job to do.' },
			{ from: 2, to: 5, clue: 'A service desk is where questions and problems land first.' },
			{ from: 5, to: 8, clue: 'A service key is the staff version that opens the right doors.' },
		],
	},
	{
		solution: [
			{ word: 'Camera', emoji: '📷' },
			{ word: 'Roll', emoji: '🎞️' },
			{ word: 'Call', emoji: '📣' },
			{ word: 'Flash', emoji: '⚡' },
			{ word: 'Card', emoji: '🃏' },
			{ word: 'Trick', emoji: '🎩' },
			{ word: 'Memory', emoji: '🧠' },
			{ word: 'Stick', emoji: '🖴' },
			{ word: 'Shift', emoji: '⚙️' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A camera roll is where the latest photos sit on a phone.' },
			{ from: 1, to: 2, clue: 'A roll call reads names one by one.' },
			{ from: 3, to: 4, clue: 'A flash card is built for quick memorization.' },
			{ from: 4, to: 5, clue: 'A card trick depends on smooth hands and timing.' },
			{ from: 6, to: 7, clue: 'A memory stick is portable storage in pocket form.' },
			{ from: 7, to: 8, clue: 'A stick shift makes the driver handle the gears manually.' },
			{ from: 0, to: 3, clue: 'A camera flash fires with the shot when the light is poor.' },
			{ from: 3, to: 6, clue: 'Flash memory keeps data even when the power is off.' },
			{ from: 1, to: 4, clue: 'A roll card is a printed route or schedule card on some older transit systems.' },
			{ from: 4, to: 7, clue: 'A card and a stick can both live in the same small tech pouch.' },
			{ from: 2, to: 5, clue: 'A trick call is just another name for a prank call.' },
			{ from: 5, to: 8, clue: 'A smooth shift can feel like a neat driving trick.' },
		],
	},
	{
		solution: [
			{ word: 'Flower', emoji: '🌸' },
			{ word: 'Pot', emoji: '🪴' },
			{ word: 'Holder', emoji: '🧺' },
			{ word: 'Water', emoji: '💧' },
			{ word: 'Bottle', emoji: '🍼' },
			{ word: 'Brush', emoji: '🪥' },
			{ word: 'Garden', emoji: '🌿' },
			{ word: 'Hose', emoji: '🚿' },
			{ word: 'Reel', emoji: '🧵' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A flower pot gives roots a home.' },
			{ from: 1, to: 2, clue: 'A pot holder lets you carry heat without regret.' },
			{ from: 3, to: 4, clue: 'A water bottle goes anywhere the day gets long.' },
			{ from: 4, to: 5, clue: 'A bottle brush is built to clean what your hand cannot reach.' },
			{ from: 6, to: 7, clue: 'A garden hose is the quick answer to thirsty beds.' },
			{ from: 7, to: 8, clue: 'A hose reel keeps the coil from turning into a mess.' },
			{ from: 0, to: 3, clue: 'Flowers need water before they need anything fancy.' },
			{ from: 3, to: 6, clue: 'You water a garden long before harvest shows up.' },
			{ from: 1, to: 4, clue: 'A bottle can be used to water a small pot in a pinch.' },
			{ from: 4, to: 7, clue: 'A hose can fill a bottle in seconds.' },
			{ from: 2, to: 5, clue: 'A brush holder is a normal bit of sink-side storage.' },
			{ from: 5, to: 8, clue: 'A brush reel is the rotating cleaner used on some sweepers and machines.' },
		],
	},
	{
		solution: [
			{ word: 'Paint', emoji: '🎨' },
			{ word: 'Tape', emoji: '🩹' },
			{ word: 'Box', emoji: '📦' },
			{ word: 'Roller', emoji: '🧻' },
			{ word: 'Measure', emoji: '📏' },
			{ word: 'Cutter', emoji: '✂️' },
			{ word: 'Tray', emoji: '🍽️' },
			{ word: 'Mark', emoji: '✏️' },
			{ word: 'Tool', emoji: '🛠️' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Paint tape protects the edge you do not want to hit.' },
			{ from: 1, to: 2, clue: 'A box of tape is workshop shelf material.' },
			{ from: 3, to: 4, clue: 'A roller can help you measure out a smooth, even coat across a wall.' },
			{ from: 4, to: 5, clue: 'Measure twice before the cutter does anything permanent.' },
			{ from: 6, to: 7, clue: 'A tray can be marked so different paints stay sorted.' },
			{ from: 7, to: 8, clue: 'A marking tool exists for wood, tile, and metal work.' },
			{ from: 0, to: 3, clue: 'A paint roller covers large walls fast.' },
			{ from: 3, to: 6, clue: 'A roller tray keeps the paint at the right depth.' },
			{ from: 1, to: 4, clue: 'A tape measure is in nearly every tool bag.' },
			{ from: 4, to: 7, clue: 'A measure mark is the line that tells you where to cut.' },
			{ from: 2, to: 5, clue: 'A box cutter is made for cardboard and packing jobs.' },
			{ from: 5, to: 8, clue: 'A cutter is one kind of tool nobody lends casually.' },
		],
	},
	{
		solution: [
			{ word: 'Horse', emoji: '🐎' },
			{ word: 'Shoe', emoji: '👟' },
			{ word: 'Lace', emoji: '🧵' },
			{ word: 'Race', emoji: '🏁' },
			{ word: 'Track', emoji: '🛤️' },
			{ word: 'Field', emoji: '🏟️' },
			{ word: 'Guard', emoji: '🛡️' },
			{ word: 'Dog', emoji: '🐕' },
			{ word: 'House', emoji: '🏠' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A horseshoe is the classic metal pairing.' },
			{ from: 1, to: 2, clue: 'A shoelace keeps the fit from coming apart.' },
			{ from: 3, to: 4, clue: 'A race track exists for speed and nothing else.' },
			{ from: 4, to: 5, clue: 'Track and field share the same meet for a reason.' },
			{ from: 6, to: 7, clue: 'A guard dog is hired with teeth included.' },
			{ from: 7, to: 8, clue: 'A doghouse is where mistakes get remembered.' },
			{ from: 0, to: 3, clue: 'A horse race is one of the oldest sporting phrases around.' },
			{ from: 3, to: 6, clue: 'A race guard or marshal keeps spectators where they belong.' },
			{ from: 1, to: 4, clue: 'A track shoe is built for grip and speed.' },
			{ from: 4, to: 7, clue: 'Dogs race on tracks too, in the greyhound version of the sport.' },
			{ from: 2, to: 5, clue: 'A lace can be part of a field uniform if it is stitched or tied on the gear.' },
			{ from: 5, to: 8, clue: 'A field house is the building at the edge of the action.' },
		],
	},
	{
		solution: [
			{ word: 'Apple', emoji: '🍎' },
			{ word: 'Tree', emoji: '🌳' },
			{ word: 'House', emoji: '🏠' },
			{ word: 'Pie', emoji: '🥧' },
			{ word: 'Dish', emoji: '🍽️' },
			{ word: 'Soap', emoji: '🧼' },
			{ word: 'Cider', emoji: '🍎🥤' },
			{ word: 'Press', emoji: '🗞️' },
			{ word: 'Box', emoji: '📦' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'An apple tree earns its keep every autumn.' },
			{ from: 1, to: 2, clue: 'A tree house is childhood architecture at its best.' },
			{ from: 3, to: 4, clue: 'A pie dish gives the crust its shape.' },
			{ from: 4, to: 5, clue: 'Dish soap belongs exactly where the plates pile up.' },
			{ from: 6, to: 7, clue: 'A cider press turns fruit into the drink.' },
			{ from: 7, to: 8, clue: 'A press box sits above the field or court.' },
			{ from: 0, to: 3, clue: 'Apple pie is the familiar dessert phrase here.' },
			{ from: 3, to: 6, clue: 'Pie and cider are a classic apple-season pairing.' },
			{ from: 1, to: 4, clue: 'A dish can be carried out under a tree at a picnic without any trouble.' },
			{ from: 4, to: 7, clue: 'A dish gets pressed flat in plenty of kitchens, from tortillas to sandwiches.' },
			{ from: 2, to: 5, clue: 'Soap belongs in every house whether you notice it or not.' },
			{ from: 5, to: 8, clue: 'A soapbox is the old-fashioned platform for a loud opinion.' },
		],
	},
	{
		solution: [
			{ word: 'Soap', emoji: '🧼' },
			{ word: 'Dish', emoji: '🍽️' },
			{ word: 'Towel', emoji: '🧻' },
			{ word: 'Shower', emoji: '🚿' },
			{ word: 'Curtain', emoji: '🪟' },
			{ word: 'Ring', emoji: '💍' },
			{ word: 'Tooth', emoji: '🦷' },
			{ word: 'Brush', emoji: '🪥' },
			{ word: 'Holder', emoji: '🧴' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A soap dish keeps the bar from sliding away.' },
			{ from: 1, to: 2, clue: 'A dish towel dries what the sink leaves behind.' },
			{ from: 3, to: 4, clue: 'A shower curtain keeps the floor out of danger.' },
			{ from: 4, to: 5, clue: 'Curtain rings let the panel glide across the rod.' },
			{ from: 6, to: 7, clue: 'A toothbrush handles the twice-daily routine.' },
			{ from: 7, to: 8, clue: 'A brush holder keeps the counter less chaotic.' },
			{ from: 0, to: 3, clue: 'Soap is one of the first things you expect to find in a shower.' },
			{ from: 3, to: 6, clue: 'A shower is one way to clean up after a rough tooth-brushing morning, even if the brush started it.' },
			{ from: 1, to: 4, clue: 'A dish can hang behind a curtain in a theatrical prop cupboard just as easily as anywhere else.' },
			{ from: 4, to: 7, clue: 'A brush can disappear behind a bathroom curtain with the rest of the cleaning kit.' },
			{ from: 2, to: 5, clue: 'A towel ring is a standard bathroom fitting.' },
			{ from: 5, to: 8, clue: 'A ring holder keeps jewelry safe while you wash up.' },
		],
	},
	{
		solution: [
			{ word: 'Coffee', emoji: '☕' },
			{ word: 'Break', emoji: '⏸️' },
			{ word: 'Room', emoji: '🚪' },
			{ word: 'Cake', emoji: '🎂' },
			{ word: 'Stand', emoji: '🪧' },
			{ word: 'Mixer', emoji: '🥣' },
			{ word: 'Mug', emoji: '🍺' },
			{ word: 'Shot', emoji: '🥃' },
			{ word: 'Service', emoji: '🛎️' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A coffee break is the civilized answer to low energy.' },
			{ from: 1, to: 2, clue: 'A break room is where the microwave always smells busy.' },
			{ from: 3, to: 4, clue: 'A cake stand lifts dessert into center-stage territory.' },
			{ from: 4, to: 5, clue: 'A stand mixer saves your arms from the hard part.' },
			{ from: 6, to: 7, clue: 'A mug shot is the phrase no one wants attached to their name.' },
			{ from: 7, to: 8, clue: 'A shot can be part of bar service as easily as table service.' },
			{ from: 0, to: 3, clue: 'Coffee cake is built for mornings and second cups.' },
			{ from: 3, to: 6, clue: 'A mug can hold cake batter before the microwave does the rest.' },
			{ from: 1, to: 4, clue: 'A stand offers a place to pause, wait, or take a break.' },
			{ from: 4, to: 7, clue: 'A shot stand is the kind of temporary counter you see at festivals and fairs.' },
			{ from: 2, to: 5, clue: 'A room can easily hold a mixer, whether it is a kitchen or a party space.' },
			{ from: 5, to: 8, clue: 'A mixer is part of drink service almost by definition.' },
		],
	},
	{
		solution: [
			{ word: 'Bus', emoji: '🚌' },
			{ word: 'Stop', emoji: '🛑' },
			{ word: 'Sign', emoji: '🪧' },
			{ word: 'Train', emoji: '🚆' },
			{ word: 'Station', emoji: '🚉' },
			{ word: 'Wagon', emoji: '🚃' },
			{ word: 'Hotel', emoji: '🏨' },
			{ word: 'Room', emoji: '🛏️' },
			{ word: 'Key', emoji: '🔑' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A bus stop is where the waiting line begins.' },
			{ from: 1, to: 2, clue: 'A stop sign makes the instruction very plain.' },
			{ from: 3, to: 4, clue: 'A train station is built around arrivals and departures.' },
			{ from: 4, to: 5, clue: 'A station wagon is the family-car phrase hidden here.' },
			{ from: 6, to: 7, clue: 'A hotel room is the reason you dragged the suitcase upstairs.' },
			{ from: 7, to: 8, clue: 'A room key is the first thing you do not want to lose.' },
			{ from: 0, to: 3, clue: 'A bus and a train are two of the most ordinary ways to move a crowd.' },
			{ from: 3, to: 6, clue: 'A hotel may run a train-themed shuttle or sit right beside the line.' },
			{ from: 1, to: 4, clue: 'A station is, at heart, still a stop with a timetable.' },
			{ from: 4, to: 7, clue: 'A station can contain waiting rooms, and a hotel certainly does.' },
			{ from: 2, to: 5, clue: 'A sign can hang on a wagon just as easily as on a wall.' },
			{ from: 5, to: 8, clue: 'A wagon can need a key if it is the motorized kind.' },
		],
	},
];

// Review: I avoided highly flexible connectors like Line, Houseboat-style splitters, Game, Light, Water, and Ball where possible, because they create too many equally believable alternate links in standard boards.