name = "lextension"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
main = ".svelte-kit/cloudflare/_worker.js"

routes = [
  { pattern = "lextension.net", custom_domain = true },
]

[vars]
PUBLIC_GA_MEASUREMENT_ID = ""

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[[kv_namespaces]]
binding = "LINK_CACHE"
id = "84e6a49904a64b1d8fd5f5793f3f0971"
